In [1]:
import pandas as pd
df_1=pd.read_csv("CPI.csv", encoding = "ISO-8859-1")
df_1.head(100)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.964552,100.0,104.316332,104.971363,102.481166,102.913266,103.402172,102.485245,101.991968,NaN
1,Afghanistan,AFG,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.867911,100.0,111.804186,119.005731,127.795223,133.768367,132.883209,138.708665,145.610741,NaN
2,Angola,AGO,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,87.359396,100.0,113.482468,125.146088,136.131179,146.042056,161.052326,213.197420,280.763277,NaN
3,Albania,ALB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,96.510765,100.0,103.442836,105.549369,107.581663,109.317001,111.404974,112.825527,115.075187,NaN
4,Andorra,AND,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,United Arab Emirates,ARE,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,99.128446,100.0,100.877347,101.545426,102.663561,105.072324,109.348732,111.115726,113.303456,NaN
7,Argentina,ARG,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Armenia,ARM,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,92.441638,100.0,107.650008,110.403717,116.795725,120.277766,124.766161,123.014934,124.207629,NaN
9,American Samoa,ASM,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,96.739843,100.0,103.456750,106.950360,108.083497,109.261004,110.319736,109.779789,112.450169,NaN
11,Australia,AUS,Consumer price index (2010 = 100),FP.CPI.TOTL,7.960458,8.142560,8.116545,8.168574,8.402706,8.688866,...,97.164412,100.0,103.303850,105.124870,107.700312,110.379813,112.044745,113.475546,115.686785,NaN
12,Austria,AUT,Consumer price index (2010 = 100),FP.CPI.TOTL,17.824166,18.455544,19.264225,19.786050,20.551488,21.564863,...,98.218767,100.0,103.286582,105.853949,107.971196,109.705002,110.688579,111.675470,113.999737,NaN
13,Azerbaijan,AZE,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,94.578400,100.0,107.852384,109.004358,111.641032,113.192537,117.730922,132.387827,149.472333,NaN
14,Burundi,BDI,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,1.468451,...,93.902651,100.0,109.592166,129.495249,139.774528,145.932088,154.023568,162.583720,188.682529,NaN
15,Belgium,BEL,Consumer price index (2010 = 100),FP.CPI.TOTL,15.596081,15.750900,15.972138,16.315220,16.995363,17.686258,...,97.857604,100.0,103.532082,106.472045,107.657181,108.023218,108.629692,110.773882,113.128903,NaN
16,Benin,BEN,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.744681,100.0,102.720908,109.648835,110.624719,109.511786,109.811484,108.879901,108.965993,NaN
17,Burkina Faso,BFA,Consumer price index (2010 = 100),FP.CPI.TOTL,10.713301,12.701918,12.914791,13.634688,13.886264,13.784859,...,100.770116,100.0,102.759767,106.683292,107.252702,106.975894,107.997506,107.733167,108.122350,NaN
18,Bangladesh,BGD,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,92.484115,100.0,111.395165,118.321164,127.231229,136.126777,144.558851,152.529140,161.226459,NaN
19,Bulgaria,BGR,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.619080,100.0,104.219904,107.299152,108.254215,106.718971,106.607307,105.755782,107.938957,NaN
20,Bahrain,BHR,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,17.965655,...,98.075865,100.0,99.598513,102.345725,105.724164,108.521933,110.518216,113.613383,115.189591,NaN
21,"Bahamas, The",BHS,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,98.673797,100.0,103.198781,105.235273,105.995508,107.592859,109.602978,109.223338,110.881575,NaN
22,Bosnia and Herzegovina,BIH,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.920664,100.0,103.671250,105.799284,105.700842,104.752500,103.680584,102.551367,103.750000,NaN
23,Belarus,BLR,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Belize,BLZ,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Bermuda,BMU,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bolivia,BOL,Consumer price index (2010 = 100),FP.CPI.TOTL,0.000022,0.000024,0.000026,0.000025,0.000028,0.000029,...,97.557858,100.0,109.884464,114.846410,121.434460,128.437100,133.651146,138.493614,142.402953,NaN
27,Brazil,BRA,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,95.202982,100.0,106.636369,112.398523,119.372104,126.927347,138.388641,150.482602,155.668786,NaN
28,Barbados,BRB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,94.496327,100.0,109.432202,114.393145,116.468355,118.529267,117.210285,118.712837,124.245074,NaN
29,Brunei Darussalam,BRN,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,99.644400,100.0,100.137912,100.249832,100.640009,100.431575,100.014662,99.275485,99.105414,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Ethiopia,ETH,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,4.697902,...,92.464799,100.0,133.249960,165.395652,178.759163,191.991263,211.403015,226.758762,249.090533,NaN
71,European Union,EUU,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Fragile and conflict affected situations,FCS,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Finland,FIN,Consumer price index (2010 = 100),FP.CPI.TOTL,8.136875,8.274470,8.637222,9.068770,10.000664,10.494756,...,98.829722,100.0,103.416807,106.321099,107.892829,109.016205,108.789529,109.177565,110.000780,NaN
74,Fiji,FJI,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,96.442339,100.0,107.282402,110.950116,114.174245,114.777220,116.356705,120.853626,124.903537,NaN
75,France,FRA,Consumer price index (2010 = 100),FP.CPI.TOTL,10.433593,10.684048,11.253644,11.816231,12.195673,12.525335,...,98.491967,100.0,102.111598,104.107058,105.006247,105.539425,105.579018,105.772581,106.864453,NaN
76,Faroe Islands,FRO,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,"Micronesia, Fed. Sts.",FSM,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,96.792575,100.0,105.082594,110.356168,112.289969,113.020174,112.683243,111.514190,112.096990,NaN
78,Gabon,GAB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,9.317640,9.984628,10.316957,10.568533,...,98.559509,100.0,101.263317,103.949244,104.474646,109.374985,109.004428,111.300832,114.252447,NaN
79,United Kingdom,GBR,Consumer price index (2010 = 100),FP.CPI.TOTL,6.273284,6.489555,6.761889,6.898381,7.124757,7.464877,...,97.567967,100.0,103.856112,106.528574,108.969854,110.551137,110.958017,112.076937,114.943592,NaN
80,Georgia,GEO,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,93.361808,100.0,108.542933,107.518658,106.968100,110.250750,114.664725,117.112733,124.180858,NaN
81,Ghana,GHA,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,0.001310,0.001657,...,90.328061,100.0,108.726837,116.475092,130.063300,150.209606,175.970507,206.685517,232.256487,NaN
82,Gibraltar,GIB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Guinea,GIN,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,86.608595,100.0,121.350466,139.826198,156.448590,171.645971,185.636612,200.808101,218.710407,NaN
84,"Gambia, The",GMB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,2.276902,2.317605,2.424588,2.314617,2.342810,...,95.193729,100.0,104.796485,109.255088,115.482333,122.350500,130.680522,140.127004,151.384956,NaN
85,Guinea-Bissau,GNB,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.543987,100.0,105.046102,107.284158,108.579212,106.940486,108.442582,110.150880,111.651299,NaN
86,Equatorial Guinea,GNQ,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,92.773703,100.0,104.805389,108.637725,111.841317,116.661677,118.617662,120.292472,121.187874,NaN
87,Greece,GRC,Consumer price index (2010 = 100),FP.CPI.TOTL,1.121350,1.144938,1.139495,1.175784,1.183042,1.221147,...,95.499151,100.0,103.329864,104.881391,103.914207,102.551673,100.771339,99.939318,101.059873,NaN
88,Grenada,GRD,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,96.677663,100.0,103.033473,105.517380,105.470953,104.433537,103.895237,105.609913,106.569335,NaN
89,Greenland,GRL,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Guatemala,GTM,Consumer price index (2010 = 100),FP.CPI.TOTL,1.755259,1.745546,1.781375,1.784073,1.780619,1.766374,...,96.283914,100.0,106.214124,110.230938,115.018677,118.950431,121.791824,127.209663,132.838101,NaN
91,Guam,GUM,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Guyana,GUY,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,96.400987,100.0,104.977736,107.488735,109.532367,110.466273,109.359694,110.273950,112.374290,NaN
93,High income,HIC,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,"Hong Kong SAR, China",HKG,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,97.738617,100.0,105.276561,109.554854,114.291535,119.364368,122.939798,125.904044,127.768157,NaN
95,Honduras,HND,Consumer price index (2010 = 100),FP.CPI.TOTL,1.561930,1.586343,1.603668,1.653085,1.727012,1.782040,...,95.511996,100.0,106.762280,112.309846,118.107167,125.346250,129.304473,132.827518,138.053432,NaN
96,Heavily indebted poor countries (HIPC),HPC,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Croatia,HRV,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,98.979957,100.0,102.272727,105.762348,108.106657,107.874016,107.372942,106.164996,107.363994,NaN
98,Haiti,HTI,Consumer price index (2010 = 100),FP.CPI.TOTL,0.616390,0.639687,0.636138,0.663535,0.724329,0.740728,...,94.610502,100.0,108.401467,115.218924,121.963232,127.532285,139.031257,158.264483,181.486751,NaN
99,Hungary,HUN,Consumer price index (2010 = 100),FP.CPI.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,95.369289,100.0,103.929921,109.804191,111.707317,111.453109,111.384404,111.824115,114.450017,NaN

In [2]:
df_2 = df_1.melt(
    id_vars = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
    value_vars = df_1.columns[4:], var_name = 'year').sort_values(['Country Name', 'year'])
df_2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
1,Afghanistan,AFG,Consumer price index (2010 = 100),FP.CPI.TOTL,1960,NaN
265,Afghanistan,AFG,Consumer price index (2010 = 100),FP.CPI.TOTL,1961,NaN
529,Afghanistan,AFG,Consumer price index (2010 = 100),FP.CPI.TOTL,1962,NaN
793,Afghanistan,AFG,Consumer price index (2010 = 100),FP.CPI.TOTL,1963,NaN
1057,Afghanistan,AFG,Consumer price index (2010 = 100),FP.CPI.TOTL,1964,NaN

In [3]:
df_3 = df_2

In [4]:
df_4 = df_3[['Country Name','year',"value"]]
df_4.columns

Index(['Country Name', 'year', 'value'], dtype='object')

In [5]:
df_4 = df_4.set_index("year")
df_4

     Country Name       value
year
1960  Afghanistan         NaN
1961  Afghanistan         NaN
1962  Afghanistan         NaN
1963  Afghanistan         NaN
1964  Afghanistan         NaN
1965  Afghanistan         NaN
1966  Afghanistan         NaN
1967  Afghanistan         NaN
1968  Afghanistan         NaN
1969  Afghanistan         NaN
1970  Afghanistan         NaN
1971  Afghanistan         NaN
1972  Afghanistan         NaN
1973  Afghanistan         NaN
1974  Afghanistan         NaN
1975  Afghanistan         NaN
1976  Afghanistan         NaN
1977  Afghanistan         NaN
1978  Afghanistan         NaN
1979  Afghanistan         NaN
1980  Afghanistan         NaN
1981  Afghanistan         NaN
1982  Afghanistan         NaN
1983  Afghanistan         NaN
1984  Afghanistan         NaN
1985  Afghanistan         NaN
1986  Afghanistan         NaN
1987  Afghanistan         NaN
1988  Afghanistan         NaN
1989  Afghanistan         NaN
...           ...         ...
1989     Zimbabwe         NaN
1990     Zimbabwe         NaN
1991     Zimbabwe         NaN
1992     Zimbabwe         NaN
1993     Zimbabwe         NaN
1994     Zimbabwe         NaN
1995     Zimbabwe         NaN
1996     Zimbabwe         NaN
1997     Zimbabwe         NaN
1998     Zimbabwe         NaN
1999     Zimbabwe         NaN
2000     Zimbabwe         NaN
2001     Zimbabwe         NaN
2002     Zimbabwe         NaN
2003     Zimbabwe         NaN
2004     Zimbabwe         NaN
2005     Zimbabwe         NaN
2006     Zimbabwe         NaN
2007     Zimbabwe         NaN
2008     Zimbabwe         NaN
2009     Zimbabwe   97.054890
2010     Zimbabwe  100.000000
2011     Zimbabwe  103.477797
2012     Zimbabwe  107.328296
2013     Zimbabwe  109.079488
2014     Zimbabwe  108.847215
2015     Zimbabwe  106.224541
2016     Zimbabwe  104.560626
2017     Zimbabwe  105.511849
2018     Zimbabwe         NaN

[15576 rows x 2 columns]

In [6]:
df_5 = pd.read_csv("GDP_per_Capita.csv")
df_6 = df_4.rename(columns={"value":"CPI"})
year = [1990,1995,2000,2005,2010,2015,2017]
df_7=df_6.reset_index()
df_7.columns

Index(['year', 'Country Name', 'CPI'], dtype='object')

In [7]:
df_8 = df_7[pd.to_numeric(df_7["year"]).isin(year)]
df_8['year']=df_8['year'].astype(int)
df_9 = pd.read_csv("GDP_per_Capita.csv")

C:\Users\linxi\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
df_9.head()

,year,country,inflow,outflow,latitude,longitude,net_migrants,GDP per Capita
0,1990,Afghanistan,50671,3581557,33.93911,67.709953,-3530886,Data Unavailable
1,1995,Afghanistan,55794,1580390,33.93911,67.709953,-1524596,Data Unavailable
2,2000,Afghanistan,60918,2441534,33.93911,67.709953,-2380616,Data Unavailable
3,2005,Afghanistan,67045,1646074,33.93911,67.709953,-1579029,247.66414
4,2010,Afghanistan,73174,2610188,33.93911,67.709953,-2537014,550.514974

In [9]:
df_9["year"]=df_9["year"].astype(int)
df_10_merge = pd.merge(df_9,df_8,left_on=['country', 'year'],right_on=['Country Name', 'year'],how = "inner")
df_10_merge

,year,country,inflow,outflow,latitude,longitude,net_migrants,GDP per Capita,Country Name,CPI
0,1990,Afghanistan,50671,3581557,33.939110,67.709953,-3530886,Data Unavailable,Afghanistan,NaN
1,1995,Afghanistan,55794,1580390,33.939110,67.709953,-1524596,Data Unavailable,Afghanistan,NaN
2,2000,Afghanistan,60918,2441534,33.939110,67.709953,-2380616,Data Unavailable,Afghanistan,NaN
3,2005,Afghanistan,67045,1646074,33.939110,67.709953,-1579029,247.66414,Afghanistan,71.582143
4,2010,Afghanistan,73174,2610188,33.939110,67.709953,-2537014,550.514974,Afghanistan,100.000000
5,2015,Afghanistan,364151,2499786,33.939110,67.709953,-2135635,590.0764738,Afghanistan,132.883209
6,2017,Afghanistan,99345,2494308,33.939110,67.709953,-2394963,550.0684587999999,Afghanistan,145.610741
7,1990,Albania,58703,133396,41.153332,20.168331,-74693,617.2304355,Albania,NaN
8,1995,Albania,63452,441271,41.153332,20.168331,-377819,750.6044492000001,Albania,40.755979
9,2000,Albania,68202,753282,41.153332,20.168331,-685080,1126.68334,Albania,74.141289
10,2005,Albania,57570,894505,41.153332,20.168331,-836935,2673.786584,Albania,86.675568
11,2010,Albania,46939,1058328,41.153332,20.168331,-1011389,4094.360204,Albania,100.000000
12,2015,Albania,46266,1069589,41.153332,20.168331,-1023323,3952.830781,Albania,111.404974
13,2017,Albania,46666,1079680,41.153332,20.168331,-1033014,4537.5790560000005,Albania,115.075187
14,1990,Algeria,258623,904559,28.033886,1.659626,-645936,2394.42038,Algeria,15.519364
15,1995,Algeria,250204,963763,28.033886,1.659626,-713559,1444.908036,Algeria,51.931085
16,2000,Algeria,241786,1023754,28.033886,1.659626,-781968,1757.017797,Algeria,70.438128
17,2005,Algeria,190843,1587317,28.033886,1.659626,-1396474,3100.122378,Algeria,81.826078
18,2010,Algeria,209723,1628704,28.033886,1.659626,-1418981,4463.394675,Algeria,100.000000
19,2015,Algeria,231471,1784029,28.033886,1.659626,-1552558,4162.852181,Algeria,126.736646
20,2017,Algeria,240308,1791159,28.033886,1.659626,-1550851,4055.247211,Algeria,142.384203
21,1990,American Samoa,20486,1082,-14.270972,-170.132217,19404,Data Unavailable,American Samoa,NaN
22,1995,American Samoa,22301,1626,-14.270972,-170.132217,20675,Data Unavailable,American Samoa,NaN
23,2000,American Samoa,24115,2157,-14.270972,-170.132217,21958,Data Unavailable,American Samoa,NaN
24,2005,American Samoa,23552,2137,-14.270972,-170.132217,21415,8508.406915000001,American Samoa,NaN
25,2010,American Samoa,22991,1932,-14.270972,-170.132217,21059,10352.82276,American Samoa,NaN
26,2015,American Samoa,22944,1992,-14.270972,-170.132217,20952,11901.97526,American Samoa,NaN
27,2017,American Samoa,22987,1994,-14.270972,-170.132217,20993,11394.4753,American Samoa,NaN
28,1990,Andorra,38137,3786,42.546245,1.601554,34351,18878.50597,Andorra,NaN
29,1995,Andorra,39688,4186,42.546245,1.601554,35502,18461.06486,Andorra,NaN
...,...,...,...,...,...,...,...,...,...,...
1184,2015,Uruguay,72689,343125,-32.522779,-55.765835,-270436,15524.84247,Uruguay,150.098484
1185,2017,Uruguay,73407,353185,-32.522779,-55.765835,-279778,16245.59837,Uruguay,174.800034
1186,1990,Uzbekistan,1577433,534964,41.377491,64.585262,1042469,651.4192061000001,Uzbekistan,NaN
1187,1995,Uzbekistan,1433906,622866,41.377491,64.585262,811040,585.9323642,Uzbekistan,NaN
1188,2000,Uzbekistan,1323853,680138,41.377491,64.585262,643715,558.2268024,Uzbekistan,NaN
1189,2005,Uzbekistan,1246984,710458,41.377491,64.585262,536526,546.7768502,Uzbekistan,NaN
1190,2010,Uzbekistan,1140101,752599,41.377491,64.585262,387502,1377.08214,Uzbekistan,NaN
1191,2015,Uzbekistan,1094008,799088,41.377491,64.585262,294920,2137.576852,Uzbekistan,NaN
1192,2017,Uzbekistan,1083064,816681,41.377491,64.585262,266383,1533.852038,Uzbekistan,NaN
1193,1990,Vanuatu,1565,4905,-15.376706,166.959158,-3340,1080.2228890000001,Vanuatu,55.870294
1194,1995,Vanuatu,1451,5629,-15.376706,166.959158,-4178,1390.329687,Vanuatu,67.044352
1195,2000,Vanuatu,1361,6255,-15.376706,166.959158,-4894,1469.8491490000001,Vanuatu,75.146389
1196,2005,Vanuatu,1810,7248,-15.376706,166.959158,-5438,1886.4333589999999,Vanuatu,83.911319
1197,2010,Vanuatu,2191,7732,-15.376706,166.959158,-5541,2965.802434,Vanuatu,100.000000
1198,2015,Vanuatu,2278,8321,-15.376706,166.959158,-6043,2788.770919,Vanuatu,107.149433
1199,2017,Vanuatu,2315,8544,-15.376706,166.959158,-6229,3123.614591,Vanuatu,111.384589
1200,1990,Zambia,269896,64663,-13.133897,27.849332,205233,409.2579854,Zambia,0.216873
1201,1995,Zambia,232452,125688,-13.133897,27.849332,106764,416.6613811,Zambia,6.730886
1202,2000,Zambia,315441,146411,-13.133897,27.849332,169030,341.9055625,Zambia,23.828288
1203,2005,Zambia,227993,165821,-13.133897,27.849332,62172,691.3178164,Zambia,59.915778
1204,2010,Zambia,130863,202808,-13.133897,27.849332,-71945,1463.213573,Zambia,100.000000
1205,2015,Zambia,135913,254813,-13.133897,27.849332,-118900,1313.889646,Zambia,144.042061
1206,2017,Zambia,137257,264344,-13.133897,27.849332,-127087,1513.276316,Zambia,180.949079
1207,1990,Zimbabwe,598946,175924,-19.015438,29.154857,423022,862.5865882000002,Zimbabwe,NaN
1208,1995,Zimbabwe,393451,251700,-19.015438,29.154857,141751,628.1849247,Zimbabwe,NaN
1209,2000,Zimbabwe,361939,309783,-19.015438,29.154857,52156,547.3588785000001,Zimbabwe,NaN
1210,2005,Zimbabwe,320377,477879,-19.015438,29.154857,-157502,444.7605075,Zimbabwe,NaN
1211,2010,Zimbabwe,286242,813007,-19.015438,29.154857,-526765,854.8476652999999,Zimbabwe,100.000000
1212,2015,Zimbabwe,262349,965801,-19.015438,29.154857,-703452,1265.294413,Zimbabwe,106.224541
1213,2017,Zimbabwe,262349,1024059,-19.015438,29.154857,-761710,1333.395663,Zimbabwe,105.511849

In [11]:
df_11=df_10_merge.sort_values(['country', 'year']).drop('Country Name', axis=1).set_index("year")
df_11["CPI"].fillna("Data Unavailable",inplace = True)
df_11.head()

,country,inflow,outflow,latitude,longitude,net_migrants,GDP per Capita,CPI
year,,,,,,,,
1990,Afghanistan,50671,3581557,33.93911,67.709953,-3530886,Data Unavailable,Data Unavailable
1995,Afghanistan,55794,1580390,33.93911,67.709953,-1524596,Data Unavailable,Data Unavailable
2000,Afghanistan,60918,2441534,33.93911,67.709953,-2380616,Data Unavailable,Data Unavailable
2005,Afghanistan,67045,1646074,33.93911,67.709953,-1579029,247.66414,71.5821
2010,Afghanistan,73174,2610188,33.93911,67.709953,-2537014,550.514974,100

In [13]:
df_11.to_csv("project_data.csv")